#!/bin/sh
set -e

if [ -f /etc/asd.conf ]; then
	mv /etc/asd.conf /etc/asd.conf.old
	echo 'ATTENTION: MAJOR CHANGES TO ASD WITH VERSION 5.69+'
	echo '-> 1. A global /etc/asd.conf is no longer used. $HOME/.config/asd/asd.conf will be'
	echo '->    created when asd is invoked the first time.'
	echo '-> 2. A system service is no longer used. A user service is provided and can be'
	echo '->    used like this:  systemctl --user start asd.service'
	echo '-> 3. Users wanting to use overlayfs mode MUST have sudo access with nopasswd to'
	echo '->    /usr/bin/asd-overlay-helper. See the man page for an example configured with visudo.'
fi

for i in $(users); do
	su $i -c 'XDG_RUNTIME_DIR=/run/user/$UID systemctl --user daemon-reload'
	return 0
done

