#!/bin/sh
set -e
case "$1" in
        install|upgrade)

                if [ -f /usr/lib/systemd/system/asd.service ]; then
                        [ "$(systemctl is-enabled asd)" = "enabled" ] &&
                                systemctl disable asd.service &>/dev/null

                        [ "$(systemctl is-active asd)" = "active" ] &&
                                systemctl stop asd.service &>/dev/null
                fi

                ;;

        abort-upgrade)
                /bin/true
                ;;

        *)
                echo "preinst called with unknown argument \`$1'" >&2
                exit 1
                ;;
esac
exit 0

