#!/bin/sh
set -e
case "$1" in
	install|upgrade)
		
		for i in $(users); do
			if [ "$(su $i -c 'XDG_RUNTIME_DIR=/run/user/$UID systemctl --user is-active asd')" = "active" ]; then
				echo "--> Internal changes to asd require it to be stopped before the update."
				echo "--> Restart it manually:  systemctl --user start asd"
				su $i -c 'XDG_RUNTIME_DIR=/run/user/$UID systemctl --user stop asd.service'
			fi
			return 0
		done

		;;

	abort-upgrade)
		/bin/true
		;;

	*)
		echo "preinst called with unknown argument \`$1'" >&2
		exit 1
		;;
esac
exit 0
